"""campo entidad

Revision ID: 7e27ed32138c
Revises: aad92195b952
Create Date: 2024-11-13 09:23:22.762964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e27ed32138c'
down_revision: Union[str, None] = 'aad92195b952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Asistentes', sa.Column('entidad', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Asistentes', 'entidad')
    # ### end Alembic commands ###
