"""Add Documento and Asistente relationship

Revision ID: aad92195b952
Revises: 4bfe324f21f0
Create Date: 2024-10-21 15:36:43.230355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad92195b952'
down_revision: Union[str, None] = '4bfe324f21f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('nombre_documento', sa.String(), nullable=False),
    sa.Column('url_archivo', sa.String(), nullable=False),
    sa.Column('asistente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asistente_id'], ['Asistentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Documentos_id'), 'Documentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Documentos_id'), table_name='Documentos')
    op.drop_table('Documentos')
    # ### end Alembic commands ###
