"""Initial migration

Revision ID: b25906a3eb21
Revises: 
Create Date: 2024-10-17 10:34:06.682053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25906a3eb21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asistentes',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('departamento', sa.String(), nullable=False),
    sa.Column('test', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('updatedBy', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Asistentes_id'), 'Asistentes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Asistentes_id'), table_name='Asistentes')
    op.drop_table('Asistentes')
    # ### end Alembic commands ###
