"""campo entidad no nulo

Revision ID: e760402356eb
Revises: 7e27ed32138c
Create Date: 2024-11-13 09:25:24.828096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e760402356eb'
down_revision: Union[str, None] = '7e27ed32138c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Asistentes', 'entidad',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Asistentes', 'entidad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
